export const error = '#ff4747'
export const accentBlunt = '#fee685'
export const bright = '#e5e7eb'
export const accent = '#ffb900'
export const white = '#fff'
export const disabled = '#6b7280'
export const disabledAccent = '#374151'
